name: nerflets
channels:
- pytorch
dependencies:
- python=3.8
- pytorch=1.10
- torchvision
- cudatoolkit=11.3
- pip
- pip:
  - pytorch-lightning==1.5.2
  - einops==0.3.2
  - kornia==0.6.1
  - opencv-python==4.5.4.58
  - matplotlib==3.5.0
  - imageio==2.10.4
  - imageio-ffmpeg==0.4.5
  - torch_optimizer==0.3.0
  - setuptools==58.2.0
  - PyMCubes==0.1.2
  - pycollada==0.7.1
  - trimesh==3.9.1
  - pyglet==1.5.10
  - networkx==2.5
  - plyfile==0.7.2
  - open3d==0.13.0
  - configargparse==1.5.3
  - ninja
